import Link from 'next/link';
import {AccessError} from '@/lib/foundation';
import {foundation,identity} from '@/lib/server-access';
import {registries,readiness,officialSources} from '@/lib/governance';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
export async function GovernanceConsole({section}:{section:string}){
 const def=registries[section];let authorized=false;let unavailable=false;let counts:{name:string;count:number}[]=[];
 try{const result=await foundation().summary(await identity(),section);authorized=true;counts=Object.entries(result).map(([name,count])=>({name:name.replaceAll('_',' '),count}));}catch(error){unavailable=!(error instanceof AccessError);authorized=false;counts=[];}
 return <main className="governance-shell"><Link href="/" className="button secondary">← CareBridge</Link><p className="demo-banner">DEMO ENVIRONMENT — DO NOT ENTER REAL PATIENT INFORMATION</p><div className="page-heading"><div><p className="eyebrow">GOVERNANCE • SASKATCHEWAN</p><h1>{def.title}</h1><p className="muted">Production PHI remains disabled.</p></div><span className="tag amber">{authorized?'Authorized session':'Access restricted'}</span></div>
 {!authorized?<section className="panel"><h2>{unavailable?'Service unavailable':'Privileged access required'}</h2><p>{unavailable?'Access could not be verified. No protected information has been released.':'This console requires an active staff membership and a recent, server-verified MFA session. Selecting a demo workspace does not grant access.'}</p><p className="muted">Initial trusted staff provisioning: Human Review Required. Clinical publishing: Blocked. There is no self-service administrator activation.</p><Link href="/mfa" className="button primary">Verify MFA / synthetic demo</Link></section>:<section className="panel"><h2>Organization registry</h2><Table><TableHeader><TableRow><TableHead>Register</TableHead><TableHead>Recorded items</TableHead><TableHead>Availability</TableHead></TableRow></TableHeader><TableBody>{counts.map(c=><TableRow key={c.name}><TableCell>{c.name}</TableCell><TableCell>{c.count}</TableCell><TableCell>Read-only • Human Review Required</TableCell></TableRow>)}</TableBody></Table><p className="muted">Empty registries do not indicate completed reviews. Clinical publication and evidence approval: Not implemented.</p></section>}</main>
}
