CREATE TABLE transaction_assertions(value INTEGER NOT NULL CHECK(value=1));
--> statement-breakpoint
CREATE UNIQUE INDEX booked_slot ON appointments(slot_id) WHERE status='booked';
--> statement-breakpoint
CREATE UNIQUE INDEX booking_idempotency ON appointments(organization_id,actor,idempotency_key);
--> statement-breakpoint
CREATE TRIGGER slot_scope_insert BEFORE INSERT ON availability WHEN NEW.timezone<>'America/Regina' OR NEW.ends_at<=NEW.starts_at OR NOT EXISTS(SELECT 1 FROM clinics c JOIN providers p ON p.organization_id=c.organization_id WHERE c.id=NEW.clinic_id AND p.id=NEW.provider_id AND c.organization_id=NEW.organization_id) BEGIN SELECT RAISE(ABORT,'SLOT_SCOPE'); END;
--> statement-breakpoint
CREATE TRIGGER booking_scope_insert BEFORE INSERT ON appointments WHEN NEW.label<>'Demo' OR NEW.status NOT IN ('booked','cancelled') OR NOT EXISTS(SELECT 1 FROM availability s JOIN patients p ON p.organization_id=s.organization_id AND p.clinic_id=s.clinic_id JOIN care_relationships r ON r.id=NEW.relationship_id AND r.patient_id=p.id AND r.provider_id=s.provider_id AND r.clinic_id=s.clinic_id AND r.organization_id=s.organization_id WHERE s.id=NEW.slot_id AND p.id=NEW.patient_id AND s.organization_id=NEW.organization_id AND s.clinic_id=NEW.clinic_id AND p.owner_user_id=NEW.actor AND p.synthetic_label LIKE 'SYNTHETIC:%' AND r.status='active') BEGIN SELECT RAISE(ABORT,'BOOKING_SCOPE'); END;
--> statement-breakpoint
CREATE TRIGGER booking_credential_insert BEFORE INSERT ON appointments WHEN NEW.status='booked' AND NOT EXISTS(SELECT 1 FROM availability s JOIN providers p ON p.id=s.provider_id JOIN memberships m ON m.user_id=p.user_id AND m.organization_id=s.organization_id AND m.clinic_id=s.clinic_id JOIN provider_credentials c ON c.provider_id=p.id AND c.organization_id=p.organization_id WHERE s.id=NEW.slot_id AND m.status='active' AND m.role='Healthcare Professional' AND (m.expires_at IS NULL OR m.expires_at>NEW.updated_at) AND c.id=(SELECT cc.id FROM provider_credentials cc WHERE cc.provider_id=p.id AND cc.organization_id=p.organization_id ORDER BY cc.created_at DESC,cc.id DESC LIMIT 1) AND c.status='Verified' AND c.expires_at>NEW.updated_at AND c.verified_at<=NEW.updated_at AND c.evidence_id IS NOT NULL AND c.verification_source IS NOT NULL AND (c.restrictions IS NULL OR c.restrictions='')) BEGIN SELECT RAISE(ABORT,'PROVIDER_UNAVAILABLE'); END;
--> statement-breakpoint
CREATE TRIGGER booking_conflict_insert BEFORE INSERT ON appointments WHEN NEW.status='booked' AND EXISTS(SELECT 1 FROM appointments b JOIN availability old ON old.id=b.slot_id JOIN availability target ON target.id=NEW.slot_id WHERE b.id<>NEW.id AND b.status='booked' AND b.organization_id=NEW.organization_id AND old.starts_at<target.ends_at AND old.ends_at>target.starts_at AND (b.patient_id=NEW.patient_id OR old.provider_id=target.provider_id)) BEGIN SELECT RAISE(ABORT,'BOOKING_CONFLICT'); END;
--> statement-breakpoint
CREATE TRIGGER booking_audit_insert AFTER INSERT ON appointments BEGIN INSERT INTO audit_events(id,created_at,organization_id,actor,role,patient_id,resource,action,purpose,authorization_result,result,correlation_id) VALUES(lower(hex(randomblob(16))),NEW.updated_at,NEW.organization_id,NEW.actor,'Patient',NEW.patient_id,'demo-appointment:'||NEW.id,'CREATE','synthetic scheduling','allowed','success',NEW.id); END;
--> statement-breakpoint
CREATE TRIGGER slot_scope_update BEFORE UPDATE ON availability WHEN NEW.timezone<>'America/Regina' OR NEW.ends_at<=NEW.starts_at OR NOT EXISTS(SELECT 1 FROM clinics c JOIN providers p ON p.organization_id=c.organization_id WHERE c.id=NEW.clinic_id AND p.id=NEW.provider_id AND c.organization_id=NEW.organization_id) BEGIN SELECT RAISE(ABORT,'SLOT_SCOPE'); END;
--> statement-breakpoint
CREATE TRIGGER booking_scope_update BEFORE UPDATE ON appointments WHEN NEW.label<>'Demo' OR NEW.status NOT IN ('booked','cancelled') OR NOT EXISTS(SELECT 1 FROM availability s JOIN patients p ON p.organization_id=s.organization_id AND p.clinic_id=s.clinic_id JOIN care_relationships r ON r.id=NEW.relationship_id AND r.patient_id=p.id AND r.provider_id=s.provider_id AND r.clinic_id=s.clinic_id AND r.organization_id=s.organization_id WHERE s.id=NEW.slot_id AND p.id=NEW.patient_id AND s.organization_id=NEW.organization_id AND s.clinic_id=NEW.clinic_id AND p.owner_user_id=NEW.actor AND p.synthetic_label LIKE 'SYNTHETIC:%' AND r.status='active') BEGIN SELECT RAISE(ABORT,'BOOKING_SCOPE'); END;
--> statement-breakpoint
CREATE TRIGGER booking_credential_update BEFORE UPDATE ON appointments WHEN NEW.status='booked' AND NOT EXISTS(SELECT 1 FROM availability s JOIN providers p ON p.id=s.provider_id JOIN memberships m ON m.user_id=p.user_id AND m.organization_id=s.organization_id AND m.clinic_id=s.clinic_id JOIN provider_credentials c ON c.provider_id=p.id AND c.organization_id=p.organization_id WHERE s.id=NEW.slot_id AND m.status='active' AND m.role='Healthcare Professional' AND (m.expires_at IS NULL OR m.expires_at>NEW.updated_at) AND c.id=(SELECT cc.id FROM provider_credentials cc WHERE cc.provider_id=p.id AND cc.organization_id=p.organization_id ORDER BY cc.created_at DESC,cc.id DESC LIMIT 1) AND c.status='Verified' AND c.expires_at>NEW.updated_at AND c.verified_at<=NEW.updated_at AND c.evidence_id IS NOT NULL AND c.verification_source IS NOT NULL AND (c.restrictions IS NULL OR c.restrictions='')) BEGIN SELECT RAISE(ABORT,'PROVIDER_UNAVAILABLE'); END;
--> statement-breakpoint
CREATE TRIGGER booking_conflict_update BEFORE UPDATE ON appointments WHEN NEW.status='booked' AND EXISTS(SELECT 1 FROM appointments b JOIN availability old ON old.id=b.slot_id JOIN availability target ON target.id=NEW.slot_id WHERE b.id<>NEW.id AND b.status='booked' AND b.organization_id=NEW.organization_id AND old.starts_at<target.ends_at AND old.ends_at>target.starts_at AND (b.patient_id=NEW.patient_id OR old.provider_id=target.provider_id)) BEGIN SELECT RAISE(ABORT,'BOOKING_CONFLICT'); END;
--> statement-breakpoint
CREATE TRIGGER booking_audit_update AFTER UPDATE ON appointments BEGIN INSERT INTO audit_events(id,created_at,organization_id,actor,role,patient_id,resource,action,purpose,authorization_result,result,correlation_id) VALUES(lower(hex(randomblob(16))),NEW.updated_at,NEW.organization_id,NEW.actor,'Patient',NEW.patient_id,'demo-appointment:'||NEW.id,CASE WHEN NEW.status='cancelled' THEN 'CANCEL' ELSE 'UPDATE' END,'synthetic scheduling','allowed','success',NEW.id); END;
--> statement-breakpoint
CREATE TRIGGER immutable_booking_identity BEFORE UPDATE ON appointments WHEN NEW.organization_id<>OLD.organization_id OR NEW.clinic_id<>OLD.clinic_id OR NEW.patient_id<>OLD.patient_id OR NEW.actor<>OLD.actor OR NEW.idempotency_key<>OLD.idempotency_key BEGIN SELECT RAISE(ABORT,'IMMUTABLE_BOOKING'); END;
