import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import {readFileSync,readdirSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
const js=ts.transpile(readFileSync('lib/foundation.ts','utf8'),{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022});
const {Foundation,AccessError,hashToken,permissionMap}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const now=2000000;
async function setup(){
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
 function stmt(query,values=[]){return {bind(...v){return stmt(query,v)},async first(){return sql.prepare(query).get(...values)??null},async run(){return sql.prepare(query).run(...values)},query,values};}
 const db={prepare:q=>stmt(q),async batch(statements){sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 function insert(table,record){const keys=Object.keys(record);sql.prepare(`INSERT INTO ${table} (${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')})`).run(...Object.values(record));}
 for(const org of ['org','other'])insert('organizations',{id:org,created_at:0,name:'SYNTHETIC',status:'active'});
 for(const [clinic,org] of [['A','org'],['B','org'],['C','other']])insert('clinics',{id:clinic,created_at:0,organization_id:org,name:'SYNTHETIC'});
 for(const [role,permissions] of Object.entries(permissionMap))for(const permission of permissions)insert('role_permissions',{id:role+permission,role,permission});
 async function user(id,role,clinic='A',org='org'){
 insert('users',{id,created_at:0,subject:id,status:'active'});insert('memberships',{id:'m'+id,created_at:0,organization_id:org,user_id:id,role,clinic_id:clinic,status:'active'});
 insert('sessions',{id:'s'+id,created_at:0,organization_id:org,user_id:id,membership_id:'m'+id,token_hash:await hashToken(id),mfa_verified_at:now-1000,expires_at:now+10000});return {subject:id,token:id};}
 const doctor=await user('doc','Healthcare Professional');const admin=await user('admin','Clinic Administrator');const privacy=await user('privacy','Privacy Officer',null);const staff=await user('staff','Clinic Staff');const staffB=await user('staffB','Clinic Staff','B');
 insert('providers',{id:'provider',created_at:0,organization_id:'org',user_id:'doc',profession:'SYNTHETIC'});
 insert('provider_credentials',{id:'credential',created_at:0,organization_id:'org',provider_id:'provider',regulator:'SYNTHETIC',jurisdiction:'SK',verification_source:'SYNTHETIC',evidence_id:'SYNTHETIC',verified_at:0,expires_at:now+10000,status:'Verified'});
 for(const [id,clinic,org] of [['pA','A','org'],['pB','B','org'],['pC','C','other']])insert('patients',{id,created_at:0,organization_id:org,clinic_id:clinic,synthetic_label:'SYNTHETIC: fixture'});
 insert('processing_authorities',{id:'authority',created_at:0,organization_id:'org',patient_id:'pA',basis:'SYNTHETIC',purpose:'care',scope:'synthetic-demographics',recipient:'doc',reviewer:'SYNTHETIC',evidence:'SYNTHETIC',effective_at:0,expires_at:now+10000,status:'Approved',consent_required:1});
 insert('care_relationships',{id:'rel',created_at:0,organization_id:'org',patient_id:'pA',provider_id:'provider',clinic_id:'A',authority_id:'authority',relationship_type:'SYNTHETIC',starts_at:0,ends_at:now+10000,status:'active'});
 insert('consent_records',{id:'consent',created_at:0,organization_id:'org',patient_id:'pA',recipient:'doc',scope:'synthetic-demographics',purpose:'care',effective_at:0,expires_at:now+10000,policy_version:'demo',version:1,evidence:'SYNTHETIC',status:'Granted'});
 return {sql,db,insert,user,doctor,admin,privacy,staff,staffB,service:new Foundation(db,()=>now)};
}
async function denied(p){await assert.rejects(p,e=>e instanceof AccessError);}
test('authorized stored synthetic patient read produces durable audit',async()=>{const f=await setup();assert.equal((await f.service.patient(f.doctor,'pA')).id,'pA');assert.equal(f.sql.prepare("SELECT count(*) AS n FROM audit_events WHERE action='READ' AND result='success' AND patient_id='pA'").get().n,1);});
test('unauthenticated access rejected',async()=>{const f=await setup();await denied(f.service.patient(null,'pA'));});
test('role cannot be supplied to gain access',async()=>{const f=await setup();await denied(f.service.patient({...f.staff,role:'Healthcare Professional'},'pA'));});
for(const id of ['pB','pC','missing'])test('BOLA denied for '+id,async()=>{const f=await setup();await denied(f.service.patient(f.doctor,id));assert.equal(f.sql.prepare("SELECT count(*) AS n FROM audit_events WHERE result='denied'").get().n,1);});
for(const [name,query] of [
 ['expired credential',"UPDATE provider_credentials SET expires_at=1"],['suspended credential',"UPDATE provider_credentials SET status='Suspended'"],['revoked session',"UPDATE sessions SET revoked_at=1 WHERE id='sdoc'"],['missing relationship',"UPDATE care_relationships SET status='ended'"],['future relationship',`UPDATE care_relationships SET starts_at=${now+1}`],['expired authority',"UPDATE processing_authorities SET expires_at=1"],['wrong recipient',"UPDATE processing_authorities SET recipient='staff'"],['stale MFA',"UPDATE sessions SET mfa_verified_at=1"],['inactive organization',"UPDATE organizations SET status='pending'"],['inactive membership',"UPDATE memberships SET status='pending' WHERE id='mdoc'"]
])test(name+' denies stored patient read',async()=>{const f=await setup();f.sql.exec(query);await denied(f.service.patient(f.doctor,'pA'));});
test('newest suspended credential cannot fall back to old verified credential',async()=>{const f=await setup();f.insert('provider_credentials',{id:'new',created_at:1,organization_id:'org',provider_id:'provider',regulator:'SYNTHETIC',jurisdiction:'SK',status:'Suspended'});await denied(f.service.patient(f.doctor,'pA'));});
test('withdrawal is append-only and newest version denies read',async()=>{const f=await setup();await f.service.withdrawConsent(f.privacy,'consent');await denied(f.service.patient(f.doctor,'pA'));assert.equal(f.sql.prepare('SELECT count(*) AS n FROM consent_records').get().n,2);assert.equal(f.sql.prepare("SELECT status FROM consent_records WHERE id='consent'").get().status,'Granted');assert.equal(f.sql.prepare("SELECT count(*) AS n FROM audit_events WHERE action='CONSENT_CHANGE'").get().n,1);});
test('approved non-consent authority evaluated separately',async()=>{const f=await setup();await f.service.withdrawConsent(f.privacy,'consent');f.sql.exec('UPDATE processing_authorities SET consent_required=0');assert.equal((await f.service.patient(f.doctor,'pA')).id,'pA');});
test('Clinic A administrator cannot change Clinic B membership',async()=>{const f=await setup();await denied(f.service.assignRole(f.admin,'mstaffB','Care Coordinator'));});
test('vertical escalation and self assignment rejected',async()=>{const f=await setup();await denied(f.service.assignRole(f.admin,'mstaff','Security Officer'));await denied(f.service.assignRole(f.admin,'madmin','Healthcare Professional'));});
test('role change revokes sessions and appends audit atomically',async()=>{const f=await setup();await f.service.assignRole(f.admin,'mstaff','Care Coordinator');assert.equal(f.sql.prepare("SELECT role FROM memberships WHERE id='mstaff'").get().role,'Care Coordinator');assert.equal(f.sql.prepare("SELECT revoked_at FROM sessions WHERE id='sstaff'").get().revoked_at,now);assert.equal(f.sql.prepare("SELECT count(*) AS n FROM audit_events WHERE action='ROLE_CHANGE'").get().n,1);});
test('audit failure rolls back role change',async()=>{const f=await setup();f.sql.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test outage'); END");await assert.rejects(f.service.assignRole(f.admin,'mstaff','Care Coordinator'));assert.equal(f.sql.prepare("SELECT role FROM memberships WHERE id='mstaff'").get().role,'Clinic Staff');});
test('session is bound to chosen membership; no LIMIT 1 role ambiguity',async()=>{const f=await setup();f.insert('memberships',{id:'docB',created_at:0,organization_id:'org',user_id:'doc',role:'Healthcare Professional',clinic_id:'B',status:'active'});f.sql.exec("UPDATE sessions SET membership_id='docB' WHERE id='sdoc'");await denied(f.service.patient(f.doctor,'pA'));});
test('login issues hashed membership-bound session without fabricating MFA',async()=>{const f=await setup();const token=await f.service.login('doc','mdoc');assert.ok(token);await denied(f.service.patient({subject:'doc',token},'pA'));const session=f.sql.prepare('SELECT * FROM sessions WHERE token_hash=?').get(await hashToken(token));assert.equal(session.mfa_verified_at,null);assert.equal(session.membership_id,'mdoc');assert.equal(f.sql.prepare("SELECT count(*) AS n FROM audit_events WHERE action='LOGIN'").get().n,1);});
test('login cannot use someone else membership',async()=>{const f=await setup();await denied(f.service.login('staff','mdoc'));});
test('clinic scoped officer cannot inspect organization-wide summary',async()=>{const f=await setup();f.sql.exec("UPDATE memberships SET clinic_id='A' WHERE id='mprivacy'");await denied(f.service.summary(f.privacy,'privacy-console'));});
test('organization summary excludes other tenant records',async()=>{const f=await setup();f.insert('privacy_requests',{id:'other',created_at:0,organization_id:'other',request_type:'SYNTHETIC'});assert.equal((await f.service.summary(f.privacy,'privacy-console')).privacy_requests,0);});
test('cross-clinic relationship rejected at database layer',async()=>{const f=await setup();assert.throws(()=>f.sql.exec("UPDATE care_relationships SET clinic_id='B'"),/CLINIC_MISMATCH/);});
test('logout revokes session and audits',async()=>{const f=await setup();await f.service.logout(f.doctor);await denied(f.service.patient(f.doctor,'pA'));assert.equal(f.sql.prepare("SELECT count(*) AS n FROM audit_events WHERE action='LOGOUT'").get().n,1);});
