import test from 'node:test';import assert from 'node:assert/strict';
import {setup,now} from './fixtures.mjs';import {service} from './load-service.mjs';
const {MFA}=await service('mfa');const {totp,base32}=await service('totp');
const key='ab'.repeat(32),origin='https://carebridge.test';
test('RFC 6238 SHA1 vectors',async()=>{const secret=base32(new TextEncoder().encode('12345678901234567890'));for(const [time,expected] of [[59,'94287082'],[1111111109,'07081804'],[1111111111,'14050471'],[1234567890,'89005924'],[2000000000,'69279037'],[20000000000,'65353130']])assert.equal(await totp(secret,Math.floor(time/30),8),expected);});
test('TOTP enrollment encrypts secret, verifies and rejects replay',async()=>{const f=await setup();f.sql.exec("UPDATE sessions SET mfa_verified_at=NULL WHERE id='sprivacy'");const m=new MFA(f.db,key,origin,()=>now);const e=await m.beginTOTP(f.privacy);assert.ok(!f.sql.prepare('SELECT secret FROM mfa_factors WHERE id=?').get(e.id).secret.includes(e.secret));await m.verifyTOTP(f.privacy,e.id,await totp(e.secret,Math.floor(now/30000)));assert.equal(f.sql.prepare("SELECT mfa_verified_at FROM sessions WHERE id='sprivacy'").get().mfa_verified_at,now);await assert.rejects(m.verifyTOTP(f.privacy,e.id,await totp(e.secret,Math.floor(now/30000))));});
test('wrong TOTP does not authorize session',async()=>{const f=await setup();f.sql.exec("UPDATE sessions SET mfa_verified_at=NULL WHERE id='sprivacy'");const m=new MFA(f.db,key,origin,()=>now);const e=await m.beginTOTP(f.privacy);await assert.rejects(m.verifyTOTP(f.privacy,e.id,'wrong'));assert.equal(f.sql.prepare("SELECT mfa_verified_at FROM sessions WHERE id='sprivacy'").get().mfa_verified_at,null);});
test('recovery codes hashed and single use',async()=>{const f=await setup();const m=new MFA(f.db,key,origin,()=>now);const {codes}=await m.recoveryCodes(f.privacy);assert.equal(codes.length,8);assert.ok(!JSON.stringify(f.sql.prepare('SELECT * FROM mfa_recovery').all()).includes(codes[0]));await m.recover(f.privacy,codes[0]);await assert.rejects(m.recover(f.privacy,codes[0]));});
test('MFA-less privileged user denied consoles',async()=>{const f=await setup();f.sql.exec("UPDATE sessions SET mfa_verified_at=NULL WHERE id='sprivacy'");await assert.rejects(f.service.summary(f.privacy,'privacy-console'));});
test('recovery code generation requires recent MFA',async()=>{const f=await setup();f.sql.exec("UPDATE sessions SET mfa_verified_at=NULL WHERE id='sprivacy'");await assert.rejects(new MFA(f.db,key,origin,()=>now).recoveryCodes(f.privacy));});
test('MFA attempt rate limit enforced',async()=>{const f=await setup();const m=new MFA(f.db,key,origin,()=>now);for(let i=0;i<10;i++)await assert.rejects(m.verifyTOTP(f.privacy,'missing','000000'));await assert.rejects(m.beginTOTP(f.privacy),e=>e.status===429);});
const b64=b=>Buffer.from(b).toString('base64url');const bytes=s=>new TextEncoder().encode(s);const concat=(...a)=>new Uint8Array(Buffer.concat(a.map(x=>Buffer.from(x))));
function cbor(x){if(typeof x==='string'){const v=bytes(x);return concat(new Uint8Array([0x60+v.length]),v);}if(x instanceof Uint8Array){return concat(x.length<24?new Uint8Array([0x40+x.length]):x.length<256?new Uint8Array([0x58,x.length]):new Uint8Array([0x59,x.length>>8,x.length&255]),x);}const entries=Object.entries(x);return concat(new Uint8Array([0xa0+entries.length]),...entries.flatMap(([k,v])=>[cbor(k),cbor(v)]));}
async function authenticator(){const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const jwk=await crypto.subtle.exportKey('jwk',keys.publicKey);const cose=concat(new Uint8Array([0xa5,1,2,3,0x26,0x20,1,0x21,0x58,32]),Buffer.from(jwk.x,'base64url'),new Uint8Array([0x22,0x58,32]),Buffer.from(jwk.y,'base64url'));const id=crypto.getRandomValues(new Uint8Array(32));const rpHash=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes('carebridge.test')));return {keys,cose,id,rpHash};}
async function registration(a,challenge,testOrigin=origin){const client=bytes(JSON.stringify({type:'webauthn.create',challenge,origin:testOrigin}));const auth=concat(a.rpHash,new Uint8Array([0x45,0,0,0,0]),new Uint8Array(16),new Uint8Array([0,32]),a.id,a.cose);return {id:b64(a.id),rawId:b64(a.id),type:'public-key',clientExtensionResults:{},response:{clientDataJSON:b64(client),attestationObject:b64(cbor({fmt:'none',attStmt:{},authData:auth})),transports:['internal']}};}
function der(raw){const parts=[raw.slice(0,32),raw.slice(32)].map(x=>{let b=Buffer.from(x);while(b.length>1&&b[0]===0)b=b.subarray(1);if(b[0]&128)b=Buffer.concat([Buffer.from([0]),b]);return Buffer.concat([Buffer.from([2,b.length]),b]);});const all=Buffer.concat(parts);return Buffer.concat([Buffer.from([0x30,all.length]),all]);}
test('signed passkey enrollment and authentication verify; challenge replay denied',async()=>{const f=await setup();const m=new MFA(f.db,key,origin,()=>now);const a=await authenticator();const options=await m.options(f.privacy,'register');await m.webauthn(f.privacy,options.id,await registration(a,options.options.challenge));const login=await m.options(f.privacy,'authenticate');const client=bytes(JSON.stringify({type:'webauthn.get',challenge:login.options.challenge,origin}));const auth=concat(a.rpHash,new Uint8Array([5,0,0,0,1]));const signature=new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},a.keys.privateKey,concat(auth,new Uint8Array(await crypto.subtle.digest('SHA-256',client)))));const response={id:b64(a.id),rawId:b64(a.id),type:'public-key',clientExtensionResults:{},response:{authenticatorData:b64(auth),clientDataJSON:b64(client),signature:b64(der(signature)),userHandle:b64(bytes('privacy'))}};await m.webauthn(f.privacy,login.id,response);await assert.rejects(m.webauthn(f.privacy,login.id,response));});
test('passkey wrong origin rejected',async()=>{const f=await setup();const m=new MFA(f.db,key,origin,()=>now);const a=await authenticator();const o=await m.options(f.privacy,'register');await assert.rejects(m.webauthn(f.privacy,o.id,await registration(a,o.options.challenge,'https://evil.test')));});
