import test from 'node:test';import assert from 'node:assert/strict';
import {setup,now} from './fixtures.mjs';import {service} from './load-service.mjs';
const {Scheduling}=await service('scheduling');
async function fixture(){const f=await setup();f.pat=await f.user('pat','Patient');f.pat2=await f.user('pat2','Patient');f.patB=await f.user('patB','Patient','B');f.sql.exec("UPDATE patients SET owner_user_id='pat' WHERE id='pA';UPDATE patients SET owner_user_id='patB' WHERE id='pB'");f.insert('patients',{id:'p2',created_at:0,organization_id:'org',clinic_id:'A',owner_user_id:'pat2',synthetic_label:'SYNTHETIC: second patient'});
 for(const [id,clinic,start] of [['s1','A',now+100000],['s2','A',now+200000],['sB','B',now+300000]])f.insert('availability',{id,organization_id:'org',clinic_id:clinic,provider_id:'provider',starts_at:start,ends_at:start+50000});
 f.s=new Scheduling(f.db,()=>now);return f;}
test('Clinic A cannot read or book Clinic B slots',async()=>{const f=await fixture();assert.deepEqual((await f.s.slots(f.pat)).map(x=>x.id),['s1','s2']);await assert.rejects(f.s.book(f.pat,'pA','sB','key',1));});
for(const status of ['Expired','Suspended'])test(status+' provider cannot offer slots',async()=>{const f=await fixture();f.sql.prepare('UPDATE provider_credentials SET status=?').run(status);assert.equal((await f.s.slots(f.pat)).length,0);await assert.rejects(f.s.book(f.pat,'pA','s1','key',1));});
test('inactive clinic membership excludes slots',async()=>{const f=await fixture();f.sql.exec("UPDATE memberships SET status='pending' WHERE id='mdoc'");assert.equal((await f.s.slots(f.pat)).length,0);});
test('two concurrent bookings exactly one succeeds',async()=>{const f=await fixture();const outcomes=await Promise.allSettled([f.s.book(f.pat,'pA','s1','key1',1),f.s.book(f.pat2,'p2','s1','key2',1)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.sql.prepare('SELECT count(*) n FROM appointments').get().n,1);});
test('concurrent duplicate idempotency key creates one booking',async()=>{const f=await fixture();const results=await Promise.all([f.s.book(f.pat,'pA','s1','same',1),f.s.book(f.pat,'pA','s1','same',1)]);assert.equal(results[0].id,results[1].id);assert.equal(f.sql.prepare('SELECT count(*) n FROM appointments').get().n,1);});
test('IDOR and cross-clinic appointment view denied',async()=>{const f=await fixture();const b=await f.s.book(f.pat,'pA','s1','key',1);await assert.rejects(f.s.view(f.pat2,b.id));await assert.rejects(f.s.view(f.patB,b.id));});
test('Support Agent cannot view appointment details',async()=>{const f=await fixture();const support=await f.user('support','Support Agent');const b=await f.s.book(f.pat,'pA','s1','key',1);await assert.rejects(f.s.view(support,b.id));});
test('create reschedule cancel and view audit plus timezone',async()=>{const f=await fixture();let b=await f.s.book(f.pat,'pA','s1','key',1);assert.equal(b.label,'Demo');assert.equal(b.timezone,'America/Regina');b=await f.s.change(f.pat,b.id,1,'s2');await assert.rejects(f.s.change(f.pat,b.id,1));b=await f.s.change(f.pat,b.id,2);assert.equal(b.status,'cancelled');for(const action of ['CREATE','UPDATE','CANCEL','VIEW'])assert.ok(f.sql.prepare('SELECT count(*) n FROM audit_events WHERE action=?').get(action).n>0);});
test('missing care relationship denies every appointment read',async()=>{const f=await fixture();const b=await f.s.book(f.pat,'pA','s1','key',1);f.sql.exec("UPDATE care_relationships SET status='ended'");await assert.rejects(f.s.view(f.pat,b.id));});
test('booking audit failure rolls back reservation and relationship',async()=>{const f=await fixture();f.sql.exec("CREATE TRIGGER fail_booking_audit BEFORE INSERT ON audit_events WHEN NEW.action='CREATE' BEGIN SELECT RAISE(ABORT,'outage'); END");await assert.rejects(f.s.book(f.pat,'pA','s1','key',1));assert.equal(f.sql.prepare('SELECT count(*) n FROM appointments').get().n,0);assert.equal(f.sql.prepare('SELECT count(*) n FROM care_relationships').get().n,1);});
