'use client';
import {useState,useEffect} from 'react';
type Slot={id:string;starts_at:number;version:number};type Appointment={id:string;starts_at:number;status:string;version:number;label:string};
export default function SchedulingControls(){const [slots,setSlots]=useState<Slot[]>([]),[bookings,setBookings]=useState<Appointment[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState('');
 const format=(n:number)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Regina',dateStyle:'medium',timeStyle:'short'}).format(n);
 async function api(operation:string,body:unknown={}){const r=await fetch('/api/scheduling/'+operation,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v:any=await r.json();if(!r.ok)throw Error('Unable to complete this sample request. Verify the sample session and refresh availability.');return v;}
 async function load(){setSlots(await api('slots'));setBookings(await api('mine'));}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Unavailable');}finally{setBusy(false);}}
 useEffect(()=>{load().catch(()=>{});},[]);
 return <><p>Sample bookings • America/Regina • sample patients and provider credentials only.</p><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{const r=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace:'patient'})});if(!r.ok)throw Error('Sample scheduling unavailable');})}>Start sample scheduling</button><div className="slot-grid">{slots.map(s=><button key={s.id} className={`slot ${selected===s.id?'selected':''}`} disabled={busy} aria-pressed={selected===s.id} onClick={()=>{setSelected(s.id);setKey(crypto.randomUUID());}}>{format(s.starts_at)}</button>)}</div><button className="button primary" disabled={busy||!selected} onClick={()=>run(async()=>{const slot=slots.find(s=>s.id===selected);if(!slot)return;await api('book',{patientId:'demo-patient',slotId:slot.id,version:slot.version,idempotencyKey:key});setSelected('');})}>Book sample appointment</button>{bookings.map(b=><div key={b.id} className="panel"><strong>Sample • {format(b.starts_at)}</strong><p>{b.status}</p>{b.status==='booked'&&<div className="button-row"><button className="button secondary" disabled={busy||!selected} onClick={()=>run(async()=>{await api('reschedule',{id:b.id,version:b.version,slotId:selected});setSelected('');})}>Reschedule to selected slot</button><button className="button subtle" disabled={busy} onClick={()=>run(async()=>{await api('cancel',{id:b.id,version:b.version});})}>Cancel Demo</button></div>}</div>)}<p role="status">{busy?'Saving…':error}</p></>}
